language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
